AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template to create an S3 bucket
Resources:
  LinhClassS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: linhclass-s3-image